#!/bin/bash

if [ ! -d ~/.nvm ]; then
  cd ~/
  git clone https://github.com/creationix/nvm.git .nvm
  cd ~/.nvm
  git checkout v0.33.11
fi

function brew_upgrade_or_install {
  brew upgrade $1 || brew install $1
}

brew tap homebrew/cask-fonts # for font-source-code-pro

brew tap d12frosted/emacs-plus

ln -sf /usr/local/opt/emacs-plus/Emacs.app /Applications
brew services start d12frosted/emacs-plus/emacs-plus

brew_upgrade_or_install svn # for font-source-code-pro
brew_upgrade_or_install font-source-code-pro
brew_upgrade_or_install emacs-plus
brew_upgrade_or_install git
brew_upgrade_or_install fzf
brew_upgrade_or_install ripgrep
brew_upgrade_or_install tmux
brew_upgrade_or_install reattach-to-user-namespace
brew_upgrade_or_install macvim
brew_upgrade_or_install neovim
brew_upgrade_or_install github/gh/gh
