#!/bin/bash

if [ ! -d ~/.nvm ]; then
  cd ~/
  git clone https://github.com/creationix/nvm.git .nvm
  cd ~/.nvm
  git checkout v0.33.11
fi

brew tap homebrew/cask-fonts && brew cask install font-source-code-pro

brew tap d12frosted/emacs-plus && brew install emacs-plus

brew install git fzf tmux reattach-to-user-namespace vim neovim rbenv pyenv the_silver_searcher
